### PR TITLE
GetterSetterCheck should not fail on duplicate getter

### LINKED ISSUE #589: GetterSetterCheck should not fail on duplicate getter
Migrated from [SONARJS-904](https://jira.sonarsource.com/browse/SONARJS-904)
GetterSetterCheck (RSPEC-2376) should not fail on:
```
class C {
  get p1() { return 42; }
  get p1() { return 42; }
}
```

### PR DESCRIPTION
**Pull request by vilchik-elena**
Fixes #589

### CODE REVIEW

File: javascript-checks/src/main/java/org/sonar/javascript/checks/GetterSetterCheck.java [hunk 1]
```diff
@@ -81,7 +81,9 @@ private void raiseIssue(AccessorMethodDeclarationTree tree, String message) {
       .filter(property -> property.is(kind))
       .collect(Collectors.toMap(
         property -> getName((AccessorMethodDeclarationTree) property),
-        tree -> (AccessorMethodDeclarationTree) tree));
+        tree -> (AccessorMethodDeclarationTree) tree,
```
Comment (inverno) [inline javascript-checks/src/main/java/org/sonar/javascript/checks/GetterSetterCheck.java]: Nice!
